// This file will be auto-generated by Supabase CLI:
// npx supabase gen types typescript --local > src/types/database.ts
//
// For now, we define a minimal Database type to satisfy imports.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      categories: {
        Row: {
          id: number;
          name: string;
          slug: string;
          icon: string | null;
          description: string | null;
          is_active: boolean;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: number;
          name: string;
          slug: string;
          icon?: string | null;
          description?: string | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: number;
          name?: string;
          slug?: string;
          icon?: string | null;
          description?: string | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
        };
      };
      neighborhoods: {
        Row: {
          id: number;
          name: string;
          slug: string;
          zone: string;
          lat: number | null;
          lng: number | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: number;
          name: string;
          slug: string;
          zone: string;
          lat?: number | null;
          lng?: number | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: number;
          name?: string;
          slug?: string;
          zone?: string;
          lat?: number | null;
          lng?: number | null;
          is_active?: boolean;
          created_at?: string;
        };
      };
      profiles: {
        Row: {
          id: string;
          slug: string | null;
          first_name: string;
          last_name: string;
          phone: string;
          whatsapp: string | null;
          email: string;
          description: string | null;
          category_id: number | null;
          profile_photo_url: string | null;
          years_experience: number | null;
          availability: "available" | "busy" | "unavailable" | null;
          price_range: "low" | "medium" | "high" | "premium" | null;
          price_description: string | null;
          certifications: string[];
          certification_docs: string[];
          is_verified: boolean;
          is_active: boolean;
          is_suspended: boolean;
          tier: "free" | "paid";
          tier_expires_at: string | null;
          profile_completeness: number;
          last_active_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          slug?: string | null;
          first_name: string;
          last_name: string;
          phone: string;
          whatsapp?: string | null;
          email: string;
          description?: string | null;
          category_id?: number | null;
          profile_photo_url?: string | null;
          years_experience?: number | null;
          availability?: "available" | "busy" | "unavailable" | null;
          price_range?: "low" | "medium" | "high" | "premium" | null;
          price_description?: string | null;
          certifications?: string[];
          certification_docs?: string[];
          is_verified?: boolean;
          is_active?: boolean;
          is_suspended?: boolean;
          tier?: "free" | "paid";
          tier_expires_at?: string | null;
          profile_completeness?: number;
          last_active_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string | null;
          first_name?: string;
          last_name?: string;
          phone?: string;
          whatsapp?: string | null;
          email?: string;
          description?: string | null;
          category_id?: number | null;
          profile_photo_url?: string | null;
          years_experience?: number | null;
          availability?: "available" | "busy" | "unavailable" | null;
          price_range?: "low" | "medium" | "high" | "premium" | null;
          price_description?: string | null;
          certifications?: string[];
          certification_docs?: string[];
          is_verified?: boolean;
          is_active?: boolean;
          is_suspended?: boolean;
          tier?: "free" | "paid";
          tier_expires_at?: string | null;
          profile_completeness?: number;
          last_active_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      profile_neighborhoods: {
        Row: { profile_id: string; neighborhood_id: number };
        Insert: { profile_id: string; neighborhood_id: number };
        Update: { profile_id?: string; neighborhood_id?: number };
      };
      profile_secondary_categories: {
        Row: { profile_id: string; category_id: number };
        Insert: { profile_id: string; category_id: number };
        Update: { profile_id?: string; category_id?: number };
      };
      work_photos: {
        Row: {
          id: string;
          profile_id: string;
          url: string;
          caption: string | null;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          url: string;
          caption?: string | null;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          url?: string;
          caption?: string | null;
          sort_order?: number;
          created_at?: string;
        };
      };
      reviews: {
        Row: {
          id: string;
          profile_id: string;
          reviewer_id: string;
          contact_id: string | null;
          rating_overall: number;
          rating_punctuality: number | null;
          rating_quality: number | null;
          rating_price: number | null;
          rating_communication: number | null;
          comment: string | null;
          professional_reply: string | null;
          professional_reply_at: string | null;
          is_visible: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          reviewer_id: string;
          contact_id?: string | null;
          rating_overall: number;
          rating_punctuality?: number | null;
          rating_quality?: number | null;
          rating_price?: number | null;
          rating_communication?: number | null;
          comment?: string | null;
          is_visible?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          reviewer_id?: string;
          contact_id?: string | null;
          rating_overall?: number;
          rating_punctuality?: number | null;
          rating_quality?: number | null;
          rating_price?: number | null;
          rating_communication?: number | null;
          comment?: string | null;
          professional_reply?: string | null;
          professional_reply_at?: string | null;
          is_visible?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      contacts: {
        Row: {
          id: string;
          profile_id: string;
          searcher_name: string;
          searcher_email: string;
          searcher_phone: string | null;
          message: string | null;
          contact_method: "form" | "whatsapp" | "phone";
          user_id: string | null;
          is_read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          searcher_name: string;
          searcher_email: string;
          searcher_phone?: string | null;
          message?: string | null;
          contact_method: "form" | "whatsapp" | "phone";
          user_id?: string | null;
          is_read?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          searcher_name?: string;
          searcher_email?: string;
          searcher_phone?: string | null;
          message?: string | null;
          contact_method?: "form" | "whatsapp" | "phone";
          user_id?: string | null;
          is_read?: boolean;
          created_at?: string;
        };
      };
      favorites: {
        Row: {
          id: string;
          user_id: string;
          profile_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          profile_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          profile_id?: string;
          created_at?: string;
        };
      };
      user_roles: {
        Row: {
          id: string;
          user_id: string;
          role: "searcher" | "professional" | "admin";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          role?: "searcher" | "professional" | "admin";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          role?: "searcher" | "professional" | "admin";
          created_at?: string;
          updated_at?: string;
        };
      };
      notification_preferences: {
        Row: {
          user_id: string;
          email_contacts: boolean;
          email_reviews: boolean;
          email_quotes: boolean;
          push_contacts: boolean;
          push_reviews: boolean;
          push_quotes: boolean;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          email_contacts?: boolean;
          email_reviews?: boolean;
          email_quotes?: boolean;
          push_contacts?: boolean;
          push_reviews?: boolean;
          push_quotes?: boolean;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          email_contacts?: boolean;
          email_reviews?: boolean;
          email_quotes?: boolean;
          push_contacts?: boolean;
          push_reviews?: boolean;
          push_quotes?: boolean;
          updated_at?: string;
        };
      };
      blog_posts: {
        Row: {
          id: string;
          title: string;
          slug: string;
          content: string;
          excerpt: string | null;
          cover_image_url: string | null;
          author_id: string | null;
          status: "draft" | "published";
          published_at: string | null;
          meta_title: string | null;
          meta_description: string | null;
          tags: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          content: string;
          excerpt?: string | null;
          cover_image_url?: string | null;
          author_id?: string | null;
          status?: "draft" | "published";
          published_at?: string | null;
          meta_title?: string | null;
          meta_description?: string | null;
          tags?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          content?: string;
          excerpt?: string | null;
          cover_image_url?: string | null;
          author_id?: string | null;
          status?: "draft" | "published";
          published_at?: string | null;
          meta_title?: string | null;
          meta_description?: string | null;
          tags?: string[];
          created_at?: string;
          updated_at?: string;
        };
      };
      static_pages: {
        Row: {
          id: string;
          title: string;
          slug: string;
          content: string;
          meta_title: string | null;
          meta_description: string | null;
          is_published: boolean;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          content: string;
          meta_title?: string | null;
          meta_description?: string | null;
          is_published?: boolean;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          content?: string;
          meta_title?: string | null;
          meta_description?: string | null;
          is_published?: boolean;
          updated_at?: string;
        };
      };
      subscriptions: {
        Row: {
          id: string;
          profile_id: string;
          mercadopago_subscription_id: string | null;
          mercadopago_payer_id: string | null;
          status: "active" | "cancelled" | "expired" | "pending";
          plan_amount: number | null;
          currency: string;
          current_period_start: string | null;
          current_period_end: string | null;
          cancelled_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          mercadopago_subscription_id?: string | null;
          mercadopago_payer_id?: string | null;
          status?: "active" | "cancelled" | "expired" | "pending";
          plan_amount?: number | null;
          currency?: string;
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancelled_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          mercadopago_subscription_id?: string | null;
          mercadopago_payer_id?: string | null;
          status?: "active" | "cancelled" | "expired" | "pending";
          plan_amount?: number | null;
          currency?: string;
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancelled_at?: string | null;
          created_at?: string;
        };
      };
      quote_requests: {
        Row: {
          id: string;
          category_id: number;
          neighborhood_id: number;
          description: string;
          requester_name: string;
          requester_email: string;
          requester_phone: string | null;
          user_id: string | null;
          status: "open" | "matched" | "closed";
          created_at: string;
        };
        Insert: {
          id?: string;
          category_id: number;
          neighborhood_id: number;
          description: string;
          requester_name: string;
          requester_email: string;
          requester_phone?: string | null;
          user_id?: string | null;
          status?: "open" | "matched" | "closed";
          created_at?: string;
        };
        Update: {
          id?: string;
          category_id?: number;
          neighborhood_id?: number;
          description?: string;
          requester_name?: string;
          requester_email?: string;
          requester_phone?: string | null;
          user_id?: string | null;
          status?: "open" | "matched" | "closed";
          created_at?: string;
        };
      };
      quote_request_matches: {
        Row: {
          id: string;
          quote_request_id: string;
          profile_id: string;
          notified_at: string | null;
          responded_at: string | null;
          response: "interested" | "declined" | null;
        };
        Insert: {
          id?: string;
          quote_request_id: string;
          profile_id: string;
          notified_at?: string | null;
          responded_at?: string | null;
          response?: "interested" | "declined" | null;
        };
        Update: {
          id?: string;
          quote_request_id?: string;
          profile_id?: string;
          notified_at?: string | null;
          responded_at?: string | null;
          response?: "interested" | "declined" | null;
        };
      };
      reports: {
        Row: {
          id: string;
          reporter_id: string | null;
          target_type: "profile" | "review" | "photo";
          target_id: string;
          reason: "spam" | "fake" | "inappropriate" | "offensive" | "other";
          description: string | null;
          status: "pending" | "reviewed" | "action_taken" | "dismissed";
          admin_notes: string | null;
          reviewed_by: string | null;
          reviewed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          reporter_id?: string | null;
          target_type: "profile" | "review" | "photo";
          target_id: string;
          reason: "spam" | "fake" | "inappropriate" | "offensive" | "other";
          description?: string | null;
          status?: "pending" | "reviewed" | "action_taken" | "dismissed";
          admin_notes?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          reporter_id?: string | null;
          target_type?: "profile" | "review" | "photo";
          target_id?: string;
          reason?: "spam" | "fake" | "inappropriate" | "offensive" | "other";
          description?: string | null;
          status?: "pending" | "reviewed" | "action_taken" | "dismissed";
          admin_notes?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: {
      generate_profile_slug: {
        Args: {
          p_first_name: string;
          p_last_name: string;
          p_category_slug: string;
          p_neighborhood_slug: string;
        };
        Returns: string;
      };
      calculate_profile_completeness: {
        Args: { p_profile_id: string };
        Returns: number;
      };
    };
    Enums: {
      availability_status: "available" | "busy" | "unavailable";
      price_range: "low" | "medium" | "high" | "premium";
      tier_type: "free" | "paid";
      contact_method: "form" | "whatsapp" | "phone";
      quote_status: "open" | "matched" | "closed";
      quote_response: "interested" | "declined";
      report_target_type: "profile" | "review" | "photo";
      report_reason:
        | "spam"
        | "fake"
        | "inappropriate"
        | "offensive"
        | "other";
      report_status: "pending" | "reviewed" | "action_taken" | "dismissed";
      blog_status: "draft" | "published";
      subscription_status: "active" | "cancelled" | "expired" | "pending";
      user_role: "searcher" | "professional" | "admin";
    };
    CompositeTypes: Record<string, never>;
  };
};
